### ISSUE TITLE
How to convert a caffe model into keras model

### ISSUE THREAD

**Issue by Hippogriff** [albertomontesg/keras-model-zoo#12]
How exactly did you convert the VGG model to Keras model? I am trying to convert the [VGG-M](https://gist.github.com/ksimonyan/f194575702fae63b2829#file-readme-md) model using the [code](https://github.com/MarcBS/keras/tree/master/keras/caffe) by @MarcBS. But due to version problem, I am not able to do it. Is there any better way to it?
Did you use some different script? Did you also upgrade the .caffemodel model file before converting into keras model?

**Comment by albertomontesg** [comment]
@GodOfProbability The VGG model from Keras was not converted by me. It was found [here](https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3).
