### ISSUE TITLE
Can the pre-trained model easily transferred to be used in Tensorflow?

### ISSUE THREAD

**Issue by bryanyzhu** [albertomontesg/keras-model-zoo#5]
Hi @albertomontesg thanks for the great work. If i want to use Tensorflow to do video classification task with C3D model. is there an easy way to load the Sports-1M pre-trained model?  Thanks.

**Comment by albertomontesg** [comment]
Hi @bryanyzhu, at this moment Tensorflow does not support 3D convolution and pooling so its not possible to operate with this framework. Checking the [issues](https://github.com/tensorflow/tensorflow/pull/2213), they are finishing to work internally to implement them, so stay tuned about it. When they release this feature, it will be necessary to wait until Keras implements the 3D convolution with the Tensorflow backend and then it would be possible to work with the C3D model on Tensorflow. 
At this moment I recommend to try using Theano backend.

**Comment by bryanyzhu** [comment]
Thanks a lot, I got it. @albertomontesg

**Comment by futurely** [comment]
https://github.com/tensorflow/tensorflow/pull/2213#issuecomment-217081951

**Comment by hx173149** [comment]
example code for c3d to ufc101 dataset: https://github.com/hx173149/C3D-tensorflow
and the pretrained model sports1M have been finetuning to UCF101,you can download them from here:
https://www.dropbox.com/sh/8wcjrcadx4r31ux/AAAkz3dQ706pPO8ZavrztRCca?dl=0

**Comment by chuckcho** [comment]
Also, my instructions / scripts may be of help: https://github.com/chuckcho/c3d-keras/
